# Generated by Django 4.1.7 on 2023-02-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_pwd_userinfo_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='avail_funds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='可用资金'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='investment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='投资额'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='asset',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总资产'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='is_bind',
            field=models.BooleanField(default=0, verbose_name='是否绑定证券账户'),
        ),
    ]
