# Generated by Django 4.1.7 on 2023-03-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userinfo_avail_funds_userinfo_investment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpdtionDailyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_code', models.CharField(max_length=8, verbose_name='合约代码')),
                ('date', models.DateField(verbose_name='日期')),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='开盘价')),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='收盘价')),
                ('highest_price', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='最高价')),
                ('lowest_price', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='最低价')),
                ('transaction_num', models.IntegerField(verbose_name='成交量')),
                ('turnover', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='成交额')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_code', models.CharField(max_length=8, verbose_name='合约代码')),
                ('position_volume', models.IntegerField(verbose_name='持仓量')),
                ('bid_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='持有均价')),
                ('now_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='现价')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, verbose_name='用户名')),
                ('option_code', models.CharField(max_length=8, verbose_name='合约代码')),
                ('buy_sell', models.SmallIntegerField(choices=[(1, '购买'), (2, '出售')], verbose_name='购买或出售')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('bid_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='买价')),
                ('now_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='卖价')),
                ('date', models.DateField(verbose_name='创建时间')),
            ],
        ),
    ]
