# Generated by Django 4.1.7 on 2023-03-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_option_daily_info_delete_opdtiondailyinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option_daily_info',
            name='close_price',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='收盘价'),
        ),
        migrations.AlterField(
            model_name='option_daily_info',
            name='highest_price',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='最高价'),
        ),
        migrations.AlterField(
            model_name='option_daily_info',
            name='lowest_price',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='最低价'),
        ),
        migrations.AlterField(
            model_name='option_daily_info',
            name='open_price',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='开盘价'),
        ),
        migrations.AlterField(
            model_name='option_daily_info',
            name='turnover',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='成交额'),
        ),
    ]
