# Generated by Django 4.1.7 on 2023-03-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_fundaccount_position_delete_option_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=16, verbose_name='用户名')),
                ('strategy_name', models.CharField(max_length=16, verbose_name='策略名称')),
                ('option_code_buy', models.CharField(default='', max_length=8, verbose_name='合约代码')),
                ('option_name_buy', models.CharField(default='', max_length=20, verbose_name='合约简称')),
                ('price_buy', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='交易价格')),
                ('quantity_buy', models.IntegerField(default=0, verbose_name='数量')),
                ('option_code_sell', models.CharField(default='', max_length=8, verbose_name='合约代码')),
                ('option_name_sell', models.CharField(default='', max_length=20, verbose_name='合约简称')),
                ('price_sell', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='交易价格')),
                ('quantity_sell', models.IntegerField(default=0, verbose_name='数量')),
                ('date', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='SingleStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=16, verbose_name='用户名')),
                ('strategy_name', models.CharField(max_length=16, verbose_name='策略名称')),
                ('option_code', models.CharField(default='', max_length=8, verbose_name='合约代码')),
                ('option_name', models.CharField(default='', max_length=20, verbose_name='合约简称')),
                ('buy_sell', models.CharField(default='', max_length=8, verbose_name='买卖方向')),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='交易价格')),
                ('quantity', models.IntegerField(default=0, verbose_name='数量')),
                ('date', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='time',
            field=models.TimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='创建日期'),
        ),
    ]
