# Generated by Django 4.1.7 on 2023-03-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_compositestrategy_singlestrategy_transaction_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.TimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
