# Generated by Django 4.1.7 on 2023-03-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_transaction_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrust_id', models.CharField(default='', max_length=16, verbose_name='委托编号')),
                ('username', models.CharField(default='', max_length=16, verbose_name='用户名')),
                ('fund_account', models.CharField(default='', max_length=16, verbose_name='资金账户')),
                ('way', models.CharField(default='', max_length=16, verbose_name='下单方式')),
                ('option_code', models.CharField(default='', max_length=8, verbose_name='合约代码')),
                ('option_name', models.CharField(default='', max_length=20, verbose_name='合约简称')),
                ('buy_sell', models.CharField(default='', max_length=8, verbose_name='买卖方向')),
                ('open_close', models.CharField(default='', max_length=8, verbose_name='开平仓')),
                ('entrust_price', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='委托价格')),
                ('entrust_quantity', models.IntegerField(default=0, verbose_name='委托数量')),
                ('statue', models.CharField(default='', max_length=16, verbose_name='委托状态')),
                ('quantity', models.IntegerField(default=0, verbose_name='成交数量')),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='成交均价')),
                ('date', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
